import {useEffect,useState} from 'react';
import {api,asError} from './api';
import {emptyAdvanced,emptyItemEdit,validItemEdit,type AdvancedRequest,type AdvancedRecord,type AdvancedInfo,type AdvancedItem,type ItemEdit,type StatEdit,type StatList} from './advanced-types';
import type {ModChoice} from './mod-types';
import './advanced.css';
import {SkillDetails} from './SkillDetails';

const categories=[['climbing','Klettern'],['swimming','Schwimmen'],['jumping','Springen'],['running','Laufen'],['combat','Kampf'],['other','Weitere Skills'],['equipment','Ausrüstungs-Buffs']] as const;
export function AdvancedMods({session,info,items,value,change}:{session:number;info:AdvancedInfo;items:ModChoice[];value:AdvancedRequest|undefined;change:(q:AdvancedRequest|undefined)=>void}){
 const q=value??emptyAdvanced;const set=(patch:Partial<AdvancedRequest>)=>change({...q,...patch});
 return <div className="advanced-mods">
  <div className="advanced-intro"><h2>Welt, Ausrüstung & Skills</h2><p>B4–B11 · Änderungen werden erst mit „Vorschau berechnen“ geprüft. Alle Faktoren beziehen sich auf die Originaldaten.</p><button type="button" onClick={()=>change(undefined)}>B4–B11 zurücksetzen</button></div>
  <details className="mod-card" open><summary><strong>B4 · Welt & Reittiere</strong></summary>
   <Numeric label="Spawn-Menge in Prozent" value={q.spawn_percent} max={10000} onChange={spawn_percent=>set({spawn_percent})}/><p>100 % = Original, 300 % = ×3. Charakterzahlen und gesetzte Spawn-Limits in Terrain-/Pool-Gruppen. Null-/Sentinel-Limits bleiben erhalten. Allgemeine NPC-Respawn-Zeitgeber sind noch nicht freigegeben.</p>
   <OptionalNumber label="Patrouillen-Reset in Prozent" value={q.patrol_reset_percent??null} initial={100} min={1} max={10000} change={v=>set({patrol_reset_percent:v??undefined})}/><p>Zwei bestätigte Spawn-Patrouillen: Hidden Estate und Watergate. 100 % = drei Tage, 50 % = 36 Stunden. Ändert resetSecond dieser Stages; kein allgemeiner Respawn-Timer. Einzelwerte in Sekunden stehen im Browser.</p>
   <OptionalNumber label="Wiederbesetzung: Wartezeit in Prozent" value={q.reoccupation_delay_percent??null} initial={100} min={1} max={10000} change={v=>set({reoccupation_delay_percent:v??undefined})}/><p>108 Regeln zur Wiederbesetzung von Fraktionsgebieten. 100 % = Originalwartezeit, 50 % = halbiert. Andere Quest-Bedingungen und Zeitgeber bleiben erhalten. Spielzeiteinheit und Wirkung sind noch nicht abgenommen; Einzelausnahmen stehen im Browser.</p>
   <OptionalNumber label="Reittier-Cooldown in Sekunden" value={q.mount_cooldown} initial={0} max={604800} change={mount_cooldown=>set({mount_cooldown})}/>
   <OptionalNumber label="Reittier-Dauer in Sekunden" value={q.mount_duration} initial={1800} min={1} max={604800} change={mount_duration=>set({mount_duration})}/>
   <Toggle label="Reittiere in Städten freigeben" value={q.town_running} change={town_running=>set({town_running})}/><p>Hebt die Stadt-Laufbeschränkung und die gemeinsame Stadtflug-Abstiegsregel auf; setzt die Reittierfreigabe im MainField. Andere Stadtregeln bleiben erhalten.</p>
   <RecordBrowser rows={info.records.filter(r=>['world','mount','spawn','patrol','reoccupation'].includes(r.module))} q={q} set={set} label="Welt-Datensätze"/>
  </details>
  <details className="mod-card"><summary><strong>B5 · Blackstar</strong></summary>
   <Toggle label="Blackstar ohne Cooldown" value={q.dragon_no_cooldown} change={dragon_no_cooldown=>set({dragon_no_cooldown})}/>
   <Toggle label="Flugbeschränkungen an Regionen und Städten aufheben" value={q.dragon_regions} change={dragon_regions=>set({dragon_regions})}/><p>Entfernt Blackstar aus der Regions-Verbotsliste und deaktiviert die Stadtflug-Abstiegsregel. Die Stadtregel betrifft auch andere Flugreittiere. Quest-/Zwischensequenz-Abstiege und Höhengrenzen sind nicht erfasst; Spielabnahme steht aus.</p>
   <OptionalNumber label="Blackstar-Reitdauer in Sekunden" value={q.dragon_duration} initial={1800} min={1} max={604800} change={dragon_duration=>set({dragon_duration})}/>
   <div className="advanced-presets">{[600,1800,3600,7200].map(n=><button type="button" key={n} onClick={()=>set({dragon_duration:n})}>{n/60} Minuten</button>)}</div><p>Drachenoptionen haben Vorrang vor globalen Reittierwerten; Einzelfelder haben zuletzt Vorrang.</p>
  </details>
  <details className="mod-card"><summary><strong>B6 · Inventar & Lager</strong></summary><p>Spielerinventar, Camp-/Warenlager, Kuku und fünf Hauslager. Startplätze und Maximum getrennt bearbeiten. Startplätze dürfen das Maximum nicht überschreiten. Die Workbench begrenzt beide Werte auf 1.460 Plätze: Diesen Standarddeckel verwendet der geprüfte Inventar-Codepfad. Weitere Engine-/Save-Grenzen sind noch nicht abgenommen. Verkleinerungen können vorhandene Inhalte betreffen.</p>
   {info.records.filter(r=>r.module==='inventory').map(row=><section key={row.key}><h3>{row.name} · {row.key}</h3><Fields row={row} q={q} set={set}/></section>)}
  </details>
  <details className="mod-card"><summary><strong>B7 · Stapel</strong></summary>
   <OptionalNumber label="Globale Stapelgröße" value={q.stack_size} initial={999} min={1} max={1000000} change={stack_size=>set({stack_size})}/><p>Gilt für bereits stapelbare Items. Ausgewählte Kategorien machen zusätzlich bisher einzelne Items stapelbar. Das Engine-Maximum ist unbekannt; 1.000.000 ist die Workbench-Prüfgrenze. Bei Items mit applyMaxStackCap kann derselbe Wert auch die Gesamtmenge im Inventar begrenzen; dieser Schalter bleibt erhalten.</p>
   <div className="advanced-categories">{info.categories.map(c=><label key={c.key}><input type="checkbox" checked={q.stack_categories.includes(c.key)} onChange={e=>set({stack_categories:e.target.checked?[...q.stack_categories,c.key].sort((a,b)=>a-b):q.stack_categories.filter(k=>k!==c.key)})}/>{c.name} · {c.entries}</label>)}</div>
   <Toggle label="Experimentelle Stacks für Ausrüstung und zustandsabhängige Items" value={q.experimental_stacks} change={experimental_stacks=>set({experimental_stacks})}/>
   <p className="advanced-warning">Experimentell: Haltbarkeit, Enchants, Sockel oder Ladungen können sich zwischen Exemplaren unterscheiden. Stapeln kann solche Zustände verlieren oder zusammenführen. Noch kein Spieltest; ohne Schalter werden diese Items global ausgelassen.</p>
  </details>
  <details className="mod-card"><summary><strong>B8 · Haltbarkeit & Reparatur</strong></summary>
   <Toggle label="Kein Haltbarkeitsverlust" value={q.no_wear} change={no_wear=>set({no_wear})}/><p>Setzt die Verschleißfaktoren der Equip-Typen auf 0 und die {info.finite_endurance_items} Items mit endlicher Haltbarkeit auf den bestätigten Unbegrenzt-Wert 65535. Bereits verbrauchte Items werden dadurch nicht wiederhergestellt. Spielabnahme steht aus.</p>
   <Toggle label="Reparaturkosten auf 0" value={q.free_repair} disabled={!q.free_repair} change={()=>set({free_repair:false})}/><p>Kostenfreie Reparatur ist nicht verfügbar. Es gibt noch keinen bestätigten Tabellenpfad.{info.repair_items===0&&' Der aktuelle Build enthält keine Reparaturregeln.'}{q.free_repair&&' Entferne die aktivierte Reparaturoption, um wieder eine Vorschau erstellen zu können.'}</p>
  </details>
  <details className="mod-card"><summary><strong>B9 · Ausdauer & Geist</strong></summary><p>Kosten in Prozent: 100 = Original, 50 = halb, 0 = kostenlos für die erfassten Einträge. Erfasst Skill-/Fahrerkosten, 31 Geistverbrauchswerte zweier Eigenverbrauchs-Skills und zusätzliche Eigenkosten von {info.records.filter(r=>r.table==='buffinfo').length} Ausrüstungs-Buffs. Positive Regeneration bleibt erhalten. Die sechs Skill-Kategorien folgen internen Namen; Ausrüstungs-Buffs sind getrennt einstellbar. Einzelausnahmen haben Vorrang.</p>
   <div className="advanced-presets">{[['stamina','Ausdauer'],['spirit','Geist']].map(([resource,title])=><button type="button" key={resource} onClick={()=>set({cost_percent:{...q.cost_percent,...Object.fromEntries(categories.map(([id])=>[`${resource}:${id}`,0]))}})}>Alle erfassten {title}kosten auf 0</button>)}</div>
   <div className="advanced-costs">{categories.map(([id,label])=><section key={id}><h3>{label}</h3>{[['stamina','Ausdauer'],['spirit','Geist']].map(([resource,title])=><Numeric key={resource} label={`${label}: ${title} in Prozent`} value={q.cost_percent[`${resource}:${id}`]??100} max={10000} onChange={n=>set({cost_percent:{...q.cost_percent,[`${resource}:${id}`]:n}})}/>)}</section>)}</div>
   <RecordBrowser rows={info.records.filter(r=>r.table==='buffinfo')} q={q} set={set} label="Buff-Eigenkosten"/>
  </details>
  <details className="mod-card"><summary><strong>B10 · Skill-Browser</strong><span> · {info.records.filter(r=>r.table==='skill').length} Skills</span></summary>
   <Numeric label="Skill-Cooldowns global in Prozent" value={q.skill_cooldown_percent} max={10000} onChange={skill_cooldown_percent=>set({skill_cooldown_percent})}/><p>Einzelausnahmen haben Vorrang. Werte werden ganzzahlig abgerundet. Referenzen und Strukturfelder bleiben unverändert. Bestätigte 64-Bit-Buffwerte sind in der Detailansicht bearbeitbar.</p>
   <RecordBrowser rows={info.records.filter(r=>r.table==='skill')} q={q} set={set} label="Skills" session={session}/>
  </details>
  <details className="mod-card"><summary><strong>B11 · Item-Editor & Vorlagen</strong></summary><ItemEditor session={session} choices={items} info={info} q={q} set={set}/></details>
  <details className="mod-card"><summary>Abdeckung und offene Spieltests</summary><ul>{info.limitations.map(s=><li key={s}>{s}</li>)}</ul></details>
 </div>
}
function Toggle({label,value,change,disabled=false}:{label:string;value:boolean;change:(v:boolean)=>void;disabled?:boolean}){return <label className="mod-switch"><input type="checkbox" checked={value} disabled={disabled} onChange={e=>change(e.target.checked)}/>{label}</label>}
function Numeric({label,value,onChange,min=0,max,disabled=false}:{label:string;value:number|string;onChange:(v:number)=>void;min?:number;max:number;disabled?:boolean}){
 const [raw,setRaw]=useState(String(value));useEffect(()=>setRaw(String(value)),[value]);
 return <label className="mod-number">{label}<input type="number" aria-label={label} required step={1} min={min} max={max} value={raw} disabled={disabled} onChange={e=>{setRaw(e.target.value);const n=Number(e.target.value);if(e.target.value.trim()!==''&&Number.isSafeInteger(n)&&n>=min&&n<=max)onChange(n)}}/></label>
}
function OptionalNumber({label,value,initial,min=0,max,change}:{label:string;value:number|null;initial:number;min?:number;max:number;change:(v:number|null)=>void}){return <div><Toggle label={`${label} ändern`} value={value!==null} change={v=>change(v?initial:null)}/><Numeric label={label} value={value??initial} min={min} max={max} disabled={value===null} onChange={change}/></div>}
function Fields({row,q,set}:{row:AdvancedRecord;q:AdvancedRequest;set:(patch:Partial<AdvancedRequest>)=>void}){
 return <div className="advanced-fields">{row.fields.map(f=>{const id=`${row.table}/${row.key}/${f.name}`,active=q.fields[id]!==undefined;return <div key={id}><Toggle label={`${f.name} überschreiben`} value={active} change={on=>{const fields={...q.fields};if(on)fields[id]=f.value;else delete fields[id];set({fields})}}/><Numeric label={`${row.key}: ${f.name}`} value={q.fields[id]??f.value} min={Number(f.min)} max={Number(f.max)} disabled={!active} onChange={v=>set({fields:{...q.fields,[id]:String(v)}})}/><small>Original: {f.value} · {f.rule}</small></div>})}</div>
}
function RecordBrowser({rows,q,set,label,session}:{rows:AdvancedRecord[];q:AdvancedRequest;set:(patch:Partial<AdvancedRequest>)=>void;label:string;session?:number}){
 const [search,filter]=useState(''),[selected,select]=useState('');const filtered=rows.filter(r=>`${r.name} ${r.key} ${r.display} ${r.category}`.toLowerCase().includes(search.toLowerCase()));const row=rows.find(r=>`${r.table}/${r.key}`===selected);
 return <div className="advanced-browser"><input aria-label={`${label} suchen`} placeholder="Name, ID oder Kategorie" value={search} onChange={e=>filter(e.target.value)}/><select aria-label={`${label} auswählen`} value={selected} onChange={e=>select(e.target.value)}><option value="">Datensatz auswählen …</option>{row&&!filtered.slice(0,100).includes(row)&&<option value={selected}>{row.name} · {row.key}</option>}{filtered.slice(0,100).map(r=><option key={`${r.table}/${r.key}`} value={`${r.table}/${r.key}`}>{r.name} · {r.key}</option>)}</select><small>{Math.min(100,filtered.length)} von {filtered.length} Treffern</small>
  {row&&<section><h3>{row.name}</h3><p>{row.table} · {row.key} · Kategorie: {row.category}</p>{row.display&&<p>{row.display}</p>}{row.description&&<p>{row.description}</p>}{row.table==='skill'&&<><OptionalNumber label={`Skill ${row.key}: Cooldown in Prozent`} value={q.skill_cooldowns[row.key]??null} initial={100} max={10000} change={v=>{const skill_cooldowns={...q.skill_cooldowns};if(v===null)delete skill_cooldowns[row.key];else skill_cooldowns[row.key]=v;set({skill_cooldowns})}}/><p>Rohwerte ohne bestätigte Einheit. Kosten sind negative Werte; positive Werte geben Ressourcen zurück.</p></>}<Fields row={row} q={q} set={set}/>{row.table==="skill"&&session!==undefined&&<SkillDetails key={row.key} session={session} skill={row.key} edits={q.skill_buffs?.[row.key]??{}} change={edits=>{const next={...q.skill_buffs};if(Object.keys(edits).length)next[row.key]=edits;else delete next[row.key];set({skill_buffs:Object.keys(next).length?next:undefined})}}/>}</section>}
 </div>
}
type Template={name:string;edit:ItemEdit};
function templates():Template[]{try{const raw=localStorage.getItem('crimson-item-templates-v1')??'[]';if(raw.length>2000000)return [];const value=JSON.parse(raw);if(!Array.isArray(value)||value.length>100)return [];const seen=new Set<string>();return value.filter(t=>{if(!t||typeof t.name!=='string'||t.name.length>80||!t.name.trim()||seen.has(t.name)||!validItemEdit(t.edit))return false;seen.add(t.name);return true;});}catch{return []}}
function ItemEditor({session,choices,info,q,set}:{session:number;choices:ModChoice[];info:AdvancedInfo;q:AdvancedRequest;set:(patch:Partial<AdvancedRequest>)=>void}){
 const [search,filter]=useState(''),[key,select]=useState(0),[detail,setDetail]=useState<AdvancedItem|null>(null),[error,setError]=useState('');
 const [enchant,setEnchant]=useState(0),[stat,setStat]=useState(0),[list,setList]=useState<StatList>('static'),[amount,setAmount]=useState(100),[buff,setBuff]=useState('');
 const [copySource,setCopySource]=useState(0),[copyTarget,setCopyTarget]=useState(1);
 const [saved,setSaved]=useState<Template[]>(templates),[templateName,setTemplateName]=useState(''),[template,setTemplate]=useState('');
 useEffect(()=>{let active=true;setDetail(null);setError('');if(key)api.advancedItem(session,key).then(d=>{if(active){setDetail(d);setEnchant(d.item.enchant_levels[0]??0);setCopySource(d.item.enchant_levels[0]??0);setCopyTarget(Math.min(65535,Math.max(0,...d.item.enchant_levels)+1));setBuff('')}}).catch(e=>{if(active)setError(asError(e).message)});return()=>{active=false}},[key,session]);
 const filtered=choices.filter(i=>`${i.key} ${i.name}`.toLowerCase().includes(search.toLowerCase()));const edit=q.items[key]??emptyItemEdit;
 function apply(next:ItemEdit){set({items:{...q.items,[key]:next}})}
 function save(next:Template[]){try{localStorage.setItem('crimson-item-templates-v1',JSON.stringify(next));setSaved(next);setError('')}catch{setError('Vorlagen konnten im lokalen App-Speicher nicht gespeichert werden.')}}
 const copies=edit.enchant_copies??[],levels=[...(detail?.item.enchant_levels??[]),...copies.map(c=>c.target_level)].sort((a,b)=>a-b),hasEnchant=levels.length>0;
 const activeEnchant=levels.includes(enchant)?enchant:levels[0]??0;
 return <div className="advanced-item"><p>Stats und Buffs lassen sich pro Enchant-Stufe bearbeiten. Neue Stufen übernehmen eine Originalstufe als Vorlage. Buffs sind auf beobachtete ID/Level-Paare desselben Equip-Typs begrenzt. Vorlagen speichern Einstellungen lokal in dieser App.</p>
  <input aria-label="Editor-Item suchen" value={search} onChange={e=>filter(e.target.value)} placeholder="Itemname oder ID"/><select aria-label="Editor-Item auswählen" value={key} onChange={e=>select(Number(e.target.value))}><option value={0}>Item auswählen …</option>{key&&!filtered.slice(0,100).some(i=>i.key===key)&&<option value={key}>{choices.find(c=>c.key===key)?.name??key}</option>}{filtered.slice(0,100).map(i=><option key={i.key} value={i.key}>{i.name} · {i.key}</option>)}</select><small>{Math.min(100,filtered.length)} von {filtered.length} Treffern</small>
  {error&&<p role="alert">{error}</p>}{key&&!detail&&!error&&<p role="status">Itemstruktur wird gelesen …</p>}
  {detail&&<><p>Equip-Typ {detail.item.equip_type} · Kategorie {detail.item.category} · Original-Stapel {detail.item.stack_size}{detail.item.stack_risk?' · Stacks experimentell':''}</p>
   <OptionalNumber label="Item-Stapelgröße" value={edit.stack_size} initial={999} min={1} max={1000000} change={stack_size=>apply({...edit,stack_size})}/>
   <Toggle label="Dieses Item kostenlos reparieren" value={edit.free_repair} disabled={!edit.free_repair} change={()=>apply({...edit,free_repair:false})}/>
   <p>Kostenfreie Reparatur ist nicht verfügbar.{edit.free_repair&&' Diese Vorlage enthält eine nicht unterstützte Reparaturoption. Entferne das Häkchen; die übrigen Item-Werte bleiben erhalten.'}</p>
   <details><summary>Enchant-Stufe hinzufügen</summary><p>Kopiert Stats, Buffs und Preise einer Originalstufe. Upgrade-Freischaltungen und vorhandene Iteminstanzen ändern sich dadurch nicht. 65.535 ist die Dateiformatgrenze; maximal 64 neue Stufen pro Item.</p>
    {detail.item.can_copy_enchants?<><select aria-label="Enchant-Originalstufe" value={copySource} onChange={e=>setCopySource(Number(e.target.value))}>{detail.item.enchant_levels.map(n=><option key={n} value={n}>{n}</option>)}</select><Numeric label="Neue Enchant-Stufe" value={copyTarget} max={65535} onChange={setCopyTarget}/><button type="button" disabled={levels.includes(copyTarget)||copies.length>=64||levels.length>=256} onClick={()=>{apply({...edit,enchant_copies:[...copies,{source_level:copySource,target_level:copyTarget}]});setEnchant(copyTarget)}}>Enchant-Stufe vormerken</button>{levels.includes(copyTarget)&&<p>Diese Stufe existiert bereits oder ist vorgemerkt.</p>}</>:<p>Dieses Item besitzt keine zum Kopieren freigegebene Enchant-Struktur.</p>}
   </details>
   <label>Enchant-Stufe<select aria-label="Item-Enchant-Stufe" value={activeEnchant} disabled={!hasEnchant} onChange={e=>setEnchant(Number(e.target.value))}>{levels.map(n=><option key={n} value={n}>{n}{copies.some(c=>c.target_level===n)?' · neu':''}</option>)}</select></label>
   {!hasEnchant?<p>Dieses Item enthält keine bearbeitbare Enchant-Zeile.</p>:<>
    <div className="advanced-stat-form"><select aria-label="Item-Stat" value={stat} onChange={e=>setStat(Number(e.target.value))}><option value={0}>Stat auswählen …</option>{info.statuses.map(s=><option key={s.key} value={s.key}>{s.name} · {s.key}</option>)}</select><select aria-label="Item-Stat-Liste" value={list} onChange={e=>setList(e.target.value as StatList)}><option value="static">Statisch</option><option value="maximum">Maximum</option><option value="regeneration">Regeneration</option><option value="per_level">Pro Level</option></select><Numeric label="Item-Stat-Wert" value={amount} min={list==='per_level'?-128:-1000000000} max={list==='per_level'?127:1000000000} onChange={setAmount}/><button type="button" disabled={!stat||list==='per_level'&&(amount< -128||amount>127)} onClick={()=>{const next:StatEdit={enchant_level:activeEnchant,list,stat,value:String(amount)};apply({...edit,stats:[...edit.stats.filter(s=>!(s.enchant_level===activeEnchant&&s.list===list&&s.stat===stat)),next]})}}>Stat setzen</button></div>
    <select aria-label="Item-Buff" value={buff} onChange={e=>setBuff(e.target.value)}><option value="">Bestätigten Buff auswählen …</option>{detail.compatible_buffs.map(([id,level])=><option key={`${id}:${level}`} value={`${id}:${level}`}>Buff {id} · Level {level}</option>)}</select><button type="button" disabled={!buff} onClick={()=>{const[id,level]=buff.split(':').map(Number);apply({...edit,buffs:[...edit.buffs.filter(b=>!(b.enchant_level===activeEnchant&&b.buff===id)),{enchant_level:activeEnchant,buff:id,level}]})}}>Buff setzen</button>
   </>}
   <details><summary>Originalwerte ({detail.item.stats.length} Stats, {detail.item.buffs.length} Buffs)</summary><pre>{JSON.stringify({stats:detail.item.stats,buffs:detail.item.buffs},null,2)}</pre></details>
   <details open><summary>Vorgemerkte Werte</summary>{copies.map(c=><div key={c.target_level}>Neue Stufe {c.target_level} aus Originalstufe {c.source_level}<button type="button" onClick={()=>{const remaining=copies.filter(v=>v.target_level!==c.target_level);apply({...edit,enchant_copies:remaining.length?remaining:undefined,stats:edit.stats.filter(s=>s.enchant_level!==c.target_level),buffs:edit.buffs.filter(b=>b.enchant_level!==c.target_level)})}}>Enchant-Stufe entfernen</button></div>)}{edit.stats.map((s,i)=><div key={`${s.enchant_level}/${s.list}/${s.stat}`}>Enchant {s.enchant_level} · {info.statuses.find(v=>v.key===s.stat)?.name??s.stat} · {s.list}: {s.value}<button type="button" onClick={()=>apply({...edit,stats:edit.stats.filter((_,n)=>n!==i)})}>Stat entfernen</button></div>)}{edit.buffs.map((b,i)=><div key={`${b.enchant_level}/${b.buff}`}>Enchant {b.enchant_level} · Buff {b.buff}, Level {b.level}<button type="button" onClick={()=>apply({...edit,buffs:edit.buffs.filter((_,n)=>n!==i)})}>Buff entfernen</button></div>)}</details>
   <div className="advanced-templates"><input aria-label="Item-Vorlagenname" maxLength={80} value={templateName} placeholder="Vorlage benennen" onChange={e=>setTemplateName(e.target.value)}/><button type="button" disabled={!templateName.trim()||saved.length>=100&&!saved.some(t=>t.name===templateName.trim())} onClick={()=>save([...saved.filter(t=>t.name!==templateName.trim()),{name:templateName.trim(),edit:structuredClone(edit)}])}>Item-Vorlage speichern</button><select aria-label="Item-Vorlage" value={template} onChange={e=>setTemplate(e.target.value)}><option value="">Gespeicherte Vorlage …</option>{saved.map(t=><option key={t.name} value={t.name}>{t.name}</option>)}</select><button type="button" disabled={!saved.some(t=>t.name===template)} onClick={()=>{const t=saved.find(t=>t.name===template);if(t)apply(structuredClone(t.edit))}}>Vorlage auf Item übernehmen</button><button type="button" disabled={!template} onClick={()=>{save(saved.filter(t=>t.name!==template));setTemplate('')}}>Vorlage löschen</button></div>
  </>}
  {Object.keys(q.items).length>0&&<details open><summary>Geänderte Items ({Object.keys(q.items).length})</summary>{Object.keys(q.items).map(id=><div key={id}>{choices.find(i=>i.key===Number(id))?.name??id} · {id}<button type="button" aria-label={`Item ${id} zurücksetzen`} onClick={()=>{const items={...q.items};delete items[Number(id)];set({items})}}>Item zurücksetzen</button></div>)}</details>}
 </div>
}
