import {expect,test,type Page} from '@playwright/test';
async function fixture(page:Page,running=false,stale=false,detailsFail=false,detailsDelay=0){
  await page.addInitScript(({running,stale,detailsFail,detailsDelay})=>{
    const root=window as unknown as {isTauri:boolean;__TAURI_INTERNALS__:unknown;socketWrites:Record<string,unknown>[];bonusReadBroken:boolean};root.isTauri=true;root.socketWrites=[];root.bonusReadBroken=detailsFail;
    const stones=[{key:1002787,name:'Zerstörung III',description:'Erhöht den Angriff.',item_type:74,category:2501,tier:3,max_stack:'50',stat_keys:[],icon_key:null},{key:1002812,name:'Sturmwind III',description:'Erhöht die Angriffsgeschwindigkeit.',item_type:74,category:2501,tier:3,max_stack:'50',stat_keys:[],icon_key:null}];
    stones.push({key:1000121,name:'Flamme des Urteils',description:'Abyss-Ausrüstung.<br/><br/>Entfesselt Flammen, die zusätzlichen Feuerschaden verursachen.',item_type:74,category:2501,tier:0,max_stack:'10',stat_keys:[],icon_key:null});
    const snapshot={revision:'a'.repeat(64),game_running:running,records:[{uid:'1001416',item_key:111005,name:'Frostfluch-Plattenpanzer',baseline:0,additional:10,gems:Array.from({length:10},()=>({key:0,endurance:0}))},{uid:'1003059',item_key:1000380,name:'Plattenhelm der Schatten',baseline:1,additional:10,gems:Array.from({length:10},()=>({key:0,endurance:0}))},{uid:'1003664',item_key:1001062,name:'Elektro-Mecha-Langschwert',baseline:5,additional:10,gems:Array.from({length:10},()=>({key:0,endurance:0}))}],runtime_log:''};
    root.__TAURI_INTERNALS__={invoke:async(command:string,args:Record<string,unknown>={})=>{
      if(command==='abyss_stone_details'){await new Promise(r=>setTimeout(r,detailsDelay));if(root.bonusReadBroken)throw {message:'Lesefehler im Test'};return stones.map(s=>({key:s.key,name:s.name,description:s.description,category:2501,equip_type:0,stack_size:s.max_stack,stack_risk:false,max_endurance:65535,repair_entries:0,enchant_levels:[0],can_copy_enchants:false,stats:s.key===1002787?[{enchant_level:0,list:'static',stat:1000002,value:'3000'},{enchant_level:0,list:'static',stat:1000003,value:'0'}]:s.key===1002812?[{enchant_level:0,list:'per_level',stat:1000010,value:'3'}]:[],buffs:s.key===1000121?[{enchant_level:0,buff:1000120,level:1}]:[]}));}
      if(command==='extra_socket_candidates')return {saves:[{id:'123/slot0',label:'Slot 1 · Konto 123',modified:1791000000}],selected_save:'123/slot0',save_revision:'c'.repeat(64),items:[{uid:'2000000',item_key:1001062,name:'Weiteres Mecha-Schwert',baseline:4,location:'Inventar / Lager',eligible:!snapshot.records.some(r=>r.uid==='2000000'),extended:snapshot.records.some(r=>r.uid==='2000000'),reason:snapshot.records.some(r=>r.uid==='2000000')?'Bereits um zehn Sockel erweitert.':null},{uid:'2000001',item_key:111005,name:'Nicht unterstütztes Exemplar',baseline:0,location:'Inventar / Lager',eligible:false,extended:false,reason:'Unbekanntes Sockelformat.'}]};
      if(command==='extra_socket_add'){root.socketWrites.push(args);await new Promise(r=>setTimeout(r,100));if(stale)throw {message:'Der Spielstand wurde geändert. Bitte die Ausrüstung neu einlesen.'};snapshot.records.push({uid:'2000000',item_key:1001062,name:'Weiteres Mecha-Schwert',baseline:4,additional:10,gems:Array.from({length:10},()=>({key:0,endurance:0}))});snapshot.revision='d'.repeat(64);return {backup:'C:/Private/add.dat',snapshot:structuredClone(snapshot)};}
      if(command==='bootstrap')return {project:'C:/Test',discovery:{installations:[{path:'C:/Synthetic'}],configured_game:'C:/Synthetic',save_directories:[]},languages:[{language:'ger'}]};
      if(command==='open_catalog')return {session:1,game_path:'C:/Synthetic',info:{item_count:0,types:[],categories:[],tiers:[],stats:[],groups:[],index:{}}};
      if(command==='search_items'){const q=args.query as {text:string,item_type:number|null,offset:number};if(q.item_type!==74)return {items:[],total:0,offset:0};if(q.text==='langsam'){await new Promise(r=>setTimeout(r,800));return {items:[stones[0]],total:1,offset:0};}const all=stones.filter(x=>x.name.toLowerCase().includes(q.text.toLowerCase()));return {items:all,total:all.length,offset:0};}
      if(command==='item_icon')return {data_url:null,source:null,reason:'Synthetischer Test ohne Spielbild'};
      if(command==='extra_sockets_snapshot')return structuredClone(snapshot);
      if(command==='extra_socket_set'){root.socketWrites.push(args);await new Promise(r=>setTimeout(r,100));if(stale)throw {message:'Die Sockel wurden zwischenzeitlich geändert. Bitte neu einlesen.'};
        const r=args.request as {uid:string,index:number,gem_key:number};snapshot.records.find(x=>x.uid===r.uid)!.gems[r.index]={key:r.gem_key,endurance:r.gem_key?65535:0};snapshot.revision='b'.repeat(64);return {backup:'C:/Private/sockets.dat',snapshot:structuredClone(snapshot)};}
      throw {message:`Unexpected command ${command}`};
    }};
  },{running,stale,detailsFail,detailsDelay});
  await page.goto('/');await expect(page.locator('.workbench')).toHaveAttribute('data-ready','true');await page.getByRole('button',{name:'Zusatzsockel',exact:true}).click();await expect(page.locator('.extra-grid button')).toHaveCount(10);
}
test('selects the tenth additional Mecha socket, preserves other slots and submits once',async({page})=>{
  await fixture(page);await expect(page.locator('.extra-gear')).toContainText('10 Sockel insgesamt');await expect(page.locator('.extra-gear')).toContainText('11 Sockel insgesamt');await expect(page.locator('.extra-gear')).toContainText('15 Sockel insgesamt');
  await page.locator('.extra-gear button').filter({hasText:'Elektro-Mecha-Langschwert'}).click();await page.getByRole('button',{name:'Zusatzsockel 10 · leer',exact:true}).click();await page.locator('.extra-gems button').filter({hasText:'Zerstörung III'}).click();await expect(page.locator('.extra-detail')).toContainText('Erhöht den Angriff.');
  await page.getByRole('button',{name:'Diesen Stein einsetzen'}).dblclick();await expect(page.getByRole('status')).toContainText('Zusatzsockel 10 bestückt');await expect(page.getByRole('button',{name:'Zusatzsockel 10 · Item 1002787',exact:true})).toBeVisible();await expect(page.locator('.extra-grid button').filter({hasText:'Leer'})).toHaveCount(9);
  const calls=await page.evaluate(()=>(window as unknown as {socketWrites:{request:unknown}[]}).socketWrites);expect(calls).toHaveLength(1);expect(calls[0].request).toMatchObject({uid:'1003664',index:9,gem_key:1002787});
  await page.screenshot({path:'../.local/extra-sockets-plus10-20261004/workbench-extra-sockets.png'});
});
test('blocks changes while game is running',async({page})=>{await fixture(page,true);await page.locator('.extra-gems button').first().click();await expect(page.getByRole('button',{name:'Diesen Stein einsetzen'})).toBeDisabled();expect(await page.evaluate(()=>(window as unknown as {socketWrites:unknown[]}).socketWrites.length)).toBe(0);});
test('stale selection rejects without marking a socket occupied',async({page})=>{await fixture(page,false,true);await page.locator('.extra-gems button').first().click();await page.getByRole('button',{name:'Diesen Stein einsetzen'}).click();await expect(page.getByRole('alert')).toContainText('zwischenzeitlich geändert');await expect(page.locator('.extra-grid button').filter({hasText:'Leer'})).toHaveCount(10);});
test('a slower obsolete search cannot replace the newer result',async({page})=>{await fixture(page);await page.getByLabel('Sockelsteine suchen').fill('langsam');await page.waitForTimeout(350);await page.getByLabel('Sockelsteine suchen').fill('Sturmwind');await expect(page.locator('.extra-gems button')).toHaveCount(1);await expect(page.locator('.extra-gems')).toContainText('Sturmwind III');await page.waitForTimeout(1000);await expect(page.locator('.extra-gems')).not.toContainText('Zerstörung III');});
test('chooses an owned instance and adds ten empty sockets once',async({page})=>{await fixture(page);await page.getByLabel('Eigene Ausrüstung suchen').fill('Weiteres Mecha');await expect(page.locator('.extra-owned button')).toHaveCount(1);await page.locator('.extra-owned button').click();await page.getByRole('button',{name:'Diesen Gegenstand um +10 erweitern'}).dblclick();await expect(page.locator('.extra-gear')).toContainText('14 Sockel insgesamt');await expect(page.locator('.extra-grid button').filter({hasText:'Leer'})).toHaveCount(10);const calls=await page.evaluate(()=>(window as unknown as {socketWrites:{request:unknown}[]}).socketWrites);expect(calls).toHaveLength(1);expect(calls[0].request).toMatchObject({uid:'2000000',save:'123/slot0',save_revision:'c'.repeat(64)});await page.locator('.extra-owned button').click();await expect(page.getByRole('button',{name:'Diesen Gegenstand um +10 erweitern'})).toBeDisabled();await page.screenshot({path:'../.local/extra-sockets-plus10-20261004/workbench-extra-sockets-selection.png'});});
test('unsupported or running-game selection cannot add sockets',async({page})=>{await fixture(page,true);await page.locator('.extra-owned button').filter({hasText:'Weiteres Mecha'}).click();await expect(page.getByRole('button',{name:'Diesen Gegenstand um +10 erweitern'})).toBeDisabled();await page.locator('.extra-owned button').filter({hasText:'Nicht unterstütztes'}).click();await expect(page.locator('.extra-add-selection')).toContainText('Unbekanntes Sockelformat');await expect(page.getByRole('button',{name:'Diesen Gegenstand um +10 erweitern'})).toBeDisabled();expect(await page.evaluate(()=>(window as unknown as {socketWrites:unknown[]}).socketWrites.length)).toBe(0);});
test('stale save rejects extension without creating a new gear entry',async({page})=>{await fixture(page,false,true);await page.locator('.extra-owned button').filter({hasText:'Weiteres Mecha'}).click();await page.getByRole('button',{name:'Diesen Gegenstand um +10 erweitern'}).click();await expect(page.getByRole('alert')).toContainText('Spielstand wurde geändert');await expect(page.locator('.extra-gear button')).toHaveCount(3);});
test('shows readable attack, speed and ability effects before inserting a stone',async({page})=>{
  await fixture(page);const attack=page.locator('.extra-gems button').filter({hasText:'Zerstörung III'});await expect(attack).toContainText('Angriff +3');await expect(attack).not.toContainText('3000');await attack.click();await expect(page.locator('.stone-values')).toContainText('Angriff+3');await expect(page.locator('.stone-values')).not.toContainText('Verteidigung');
  await page.locator('.extra-gems button').filter({hasText:'Sturmwind III'}).click();await expect(page.locator('.stone-values')).toContainText('Angriffsgeschwindigkeit+3 Stufen');
  await page.locator('.extra-gems button').filter({hasText:'Flamme des Urteils'}).click();await expect(page.locator('.stone-values')).toContainText('zusätzlichen Feuerschaden');await expect(page.locator('.stone-values')).not.toContainText('Buff-ID');
  await page.locator('.extra-gems button').filter({hasText:'Zerstörung III'}).click();await page.locator('.extra-editor').scrollIntoViewIfNeeded();await page.screenshot({path:'../.local/socket-stone-effects-20261005/bonus-preview.png'});
  expect(await page.evaluate(()=>(window as unknown as {socketWrites:unknown[]}).socketWrites.length)).toBe(0);
});
test('selection changes during bonus loading never show another stone values',async({page})=>{
  await fixture(page,false,false,false,700);await page.locator('.extra-gems button').filter({hasText:'Zerstörung III'}).click();await page.locator('.extra-gems button').filter({hasText:'Sturmwind III'}).click();await expect(page.locator('.extra-detail')).toContainText('Angriffsgeschwindigkeit+3 Stufen');await expect(page.locator('.extra-detail dt')).toHaveText('Angriffsgeschwindigkeit');
});
test('a failed bonus read reports missing values and can be retried without socket writes',async({page})=>{
  await fixture(page,false,false,true);await expect(page.getByRole('alert')).toContainText('Boni konnten nicht geladen werden');await page.locator('.extra-gems button').filter({hasText:'Zerstörung III'}).click();await expect(page.locator('.extra-detail')).toContainText('Keine Werte');await page.evaluate(()=>(window as unknown as {bonusReadBroken:boolean}).bonusReadBroken=false);await page.getByRole('button',{name:'Boni erneut laden'}).click();await expect(page.locator('.stone-values')).toContainText('Angriff+3');await expect(page.getByRole('alert')).toHaveCount(0);expect(await page.evaluate(()=>(window as unknown as {socketWrites:unknown[]}).socketWrites.length)).toBe(0);
});
